### ISSUE TITLE
problem with running dev version 

### ISSUE THREAD

**Issue by idohurvitz** [igeligel/vuex-namespaced-module-structure#1]
hey,
first off all, you wrote great article at medium, it was a pleasure to read.

now for my problem,
I'm trying to play a bit with the project template for maybe a future use, and after i installed the dependencies and try run npm run dev, there is an error and the server is returning error.
i did exactly as i should.

can you please help me ?

**Comment by igeligel** [comment]
What does the error say?

**Comment by idohurvitz** [comment]
![image](https://user-images.githubusercontent.com/28308066/45926282-be2d3c00-bf29-11e8-9f0f-7968885dd691.png)

**Comment by idohurvitz** [comment]
you can close, i fix it while using css and not scss
